trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Node.js
  - task: UseNode@2
    inputs:
      version: '16.x' # Ensure it's compatible with Next.js 14

  # Step 2: Install dependencies
  - script: |
      npm install
    displayName: 'Install dependencies'

  # Step 3: Run Linter
  - script: |
      npm run lint
    displayName: 'Run Linter'

  # Step 4: Build the app
  - script: |
      npm run build
    displayName: 'Build Next.js app'

  # Step 5: Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '.next'
      artifactName: 'next-build'
      publishLocation: 'Container'
